import 'package:FocusFlow/services/settings_service.dart';

class LocalizationService {
  static final Map<String, Map<String, String>> _translations = {
    'English': {
      'profile': 'Profile',
      'settings': 'Settings',
      'notifications': 'Notifications',
      'timer_duration': 'Timer Duration',
      'customise': 'Customise',
      'sounds': 'Sounds',
      'theme': 'Theme',
      'language': 'Language',
      'log_out': 'Log Out',
      'edit_profile': 'Edit Profile',
      'display_name': 'Display Name',
      'save_changes': 'Save Changes',
      'total_sessions': 'Total Sessions',
      'focus_hours': 'Focus Hours',
      'tasks_done': 'Tasks Done',
      'current_streak': 'Current Streak',
      'achievements': 'Achievements',
      'home': 'Home',
      'focus': 'Focus',
      'tasks': 'Tasks',
      'feed': 'Feed',
      'ai': 'AI',
      'on_fire': 'On Fire',
      'speed_demon': 'Speed Demon',
      'sharpshooter': 'Sharpshooter',
      'night_owl': 'Night Owl',
      'champion': 'Champion',
      'diamond': 'Diamond',
      'streak_desc': '7-day streak',
      'sessions_desc': '10 sessions done',
      'tasks_desc': '50 tasks completed',
      'night_desc': 'Focus after midnight',
      'streak_30_desc': '30-day streak',
      'sessions_500_desc': '500 sessions total',
      'all': 'All',
      'active_filter': 'Active',
      'done_filter': 'Done',
      'tasks_remaining': 'tasks remaining',
      'completed_of': 'completed',
      'of': 'of',
      'no_tasks': 'No tasks yet. Add one!',
      'no_filter_tasks': 'No {filter} tasks',
      'new_task': 'New Task',
      'task_hint': 'What needs to be done?',
      'add_task': 'Add Task',
      'high': 'High',
      'medium': 'Medium',
      'low': 'Low',
      'pomodoro': 'Pomodoro',
      'short_break': 'Short Break',
      'long_break': 'Long Break',
      'sessions': 'sessions',
      'focus_lock_on': 'Focus Lock ON',
      'stop_timer_before_leaving': 'Stop the timer before leaving!',
      'session_saved': 'min session saved!',
      'tip1': '💡 Silence your phone for maximum focus.',
      'tip2': '🌊 Take deep breaths at the start of each session.',
      'tip3': '✅ Write your #1 task before starting the timer.',
      'tip4': '🎧 Ambient music can boost concentration.',
    },
    'Hindi': {
      'profile': 'प्रोफ़ाइल',
      'settings': 'सेटिंग्स',
      'notifications': 'सूचनाएं',
      'timer_duration': 'टाइमर की अवधि',
      'customise': 'अनुकूलित करें',
      'sounds': 'ध्वनि',
      'theme': 'थीम',
      'language': 'भाषा',
      'log_out': 'लॉग आउट',
      'edit_profile': 'प्रोफ़ाइल संपादित करें',
      'display_name': 'प्रदर्शित नाम',
      'save_changes': 'बदलाव सहेजें',
      'total_sessions': 'कुल सत्र',
      'focus_hours': 'फोकस घंटे',
      'tasks_done': 'पूरे किए गए कार्य',
      'current_streak': 'वर्तमान स्ट्रीक',
      'achievements': 'उपलब्धियां',
      'home': 'होम',
      'focus': 'फोकस',
      'tasks': 'कार्य',
      'feed': 'फ़ीड',
      'ai': 'एआई',
      'on_fire': 'जोश में',
      'speed_demon': 'गति का जादूगर',
      'sharpshooter': 'निशानेबाज',
      'night_owl': 'रात का उल्लू',
      'champion': 'चैंपियन',
      'diamond': 'हीरा',
      'streak_desc': '7-दिन की स्ट्रीक',
      'sessions_desc': '10 सत्र पूरे',
      'tasks_desc': '50 कार्य पूरे',
      'night_desc': 'आधी रात के बाद फोकस',
      'streak_30_desc': '30-दिन की स्ट्रीक',
      'sessions_500_desc': '500 कुल सत्र',
      'all': 'सभी',
      'active_filter': 'सक्रिय',
      'done_filter': 'पूर्ण',
      'tasks_remaining': 'कार्य शेष',
      'completed_of': 'पूर्ण',
      'of': 'में से',
      'no_tasks': 'अभी तक कोई कार्य नहीं। एक जोड़ें!',
      'no_filter_tasks': 'कोई {filter} कार्य नहीं',
      'new_task': 'नया कार्य',
      'task_hint': 'क्या करने की आवश्यकता है?',
      'add_task': 'कार्य जोड़ें',
      'high': 'उच्च',
      'medium': 'मध्यम',
      'low': 'निम्न',
      'pomodoro': 'पोमोडोरो',
      'short_break': 'छोटा ब्रेक',
      'long_break': 'लंबा ब्रेक',
      'sessions': 'सत्र',
      'focus_lock_on': 'फोकस लॉक चालू',
      'stop_timer_before_leaving': 'छोड़ने से पहले टाइमर रोकें!',
      'session_saved': 'मिनट का सत्र सहेजा गया! 🎉',
      'tip1': '💡 अधिकतम फोकस के लिए अपने फोन को साइलेंट करें।',
      'tip2': '🌊 प्रत्येक सत्र की शुरुआत में गहरी सांसें लें।',
      'tip3': '✅ टाइमर शुरू करने से पहले अपना #1 कार्य लिखें।',
      'tip4': '🎧 परिवेश संगीत एकाग्रता को बढ़ावा दे सकता है।',
    },
    'Spanish': {
      'profile': 'Perfil',
      'settings': 'Ajustes',
      'notifications': 'Notificaciones',
      'timer_duration': 'Duración del temporizador',
      'customise': 'Personalizar',
      'sounds': 'Sonidos',
      'theme': 'Tema',
      'language': 'Idioma',
      'log_out': 'Cerrar sesión',
      'edit_profile': 'Editar perfil',
      'display_name': 'Nombre para mostrar',
      'save_changes': 'Guardar cambios',
      'total_sessions': 'Sesiones totales',
      'focus_hours': 'Horas de enfoque',
      'tasks_done': 'Tareas hechas',
      'current_streak': 'Racha actual',
      'achievements': 'Logros',
      'home': 'Inicio',
      'focus': 'Enfoque',
      'tasks': 'Tareas',
      'feed': 'Feed',
      'ai': 'IA',
      'on_fire': 'En llamas',
      'speed_demon': 'Demonio de la velocidad',
      'sharpshooter': 'Tirador de élite',
      'night_owl': 'Búho nocturno',
      'champion': 'Campeón',
      'diamond': 'Diamante',
      'streak_desc': 'Racha de 7 días',
      'sessions_desc': '10 sesiones hechas',
      'tasks_desc': '50 tareas completadas',
      'night_desc': 'Enfoque tras medianoche',
      'streak_30_desc': 'Racha de 30 días',
      'sessions_500_desc': '500 sesiones en total',
      'all': 'Todos',
      'active_filter': 'Activos',
      'done_filter': 'Hechos',
      'tasks_remaining': 'tareas restantes',
      'completed_of': 'completadas',
      'of': 'de',
      'no_tasks': 'No hay tareas aún. ¡Añade una!',
      'no_filter_tasks': 'No hay tareas {filter}',
      'new_task': 'Nueva tarea',
      'task_hint': '¿Qué hay que hacer?',
      'add_task': 'Añadir tarea',
      'high': 'Alta',
      'medium': 'Media',
      'low': 'Baja',
      'pomodoro': 'Pomodoro',
      'short_break': 'Descanso corto',
      'long_break': 'Descanso largo',
      'sessions': 'sesiones',
      'focus_lock_on': 'Bloqueo de enfoque activado',
      'stop_timer_before_leaving': '¡Detén el temporizador antes de salir!',
      'session_saved': '¡min de sesión guardados! 🎉',
      'tip1': '💡 Silencia tu teléfono para un enfoque máximo.',
      'tip2': '🌊 Toma respiraciones profundas al inicio de cada sesión.',
      'tip3': '✅ Escribe tu tarea #1 antes de iniciar el temporizador.',
      'tip4': '🎧 La música ambiental puede aumentar la concentración.',
    },
    'French': {
      'profile': 'Profil',
      'settings': 'Paramètres',
      'notifications': 'Notifications',
      'timer_duration': 'Durée du minuteur',
      'customise': 'Personnaliser',
      'sounds': 'Sons',
      'theme': 'Thème',
      'language': 'Langue',
      'log_out': 'Déconnexion',
      'edit_profile': 'Modifier le profil',
      'display_name': 'Nom d\'affichage',
      'save_changes': 'Enregistrer',
      'total_sessions': 'Sessions totales',
      'focus_hours': 'Heures de focus',
      'tasks_done': 'Tâches terminées',
      'current_streak': 'Série actuelle',
      'achievements': 'Succès',
      'home': 'Accueil',
      'focus': 'Focus',
      'tasks': 'Tâches',
      'feed': 'Flux',
      'ai': 'IA',
      'on_fire': 'En feu',
      'speed_demon': 'Démon de la vitesse',
      'sharpshooter': 'Tireur d\'élite',
      'night_owl': 'Oiseau de nuit',
      'champion': 'Champion',
      'diamond': 'Diamant',
      'streak_desc': '7 jours de suite',
      'sessions_desc': '10 sessions faites',
      'tasks_desc': '50 tâches terminées',
      'night_desc': 'Focus après minuit',
      'streak_30_desc': '30 jours de suite',
      'sessions_500_desc': '500 sessions au total',
      'all': 'Tous',
      'active_filter': 'Actifs',
      'done_filter': 'Terminés',
      'tasks_remaining': 'tâches restantes',
      'completed_of': 'terminées',
      'of': 'sur',
      'no_tasks': 'Pas encore de tâches. Ajoutez-en une !',
      'no_filter_tasks': 'Pas de tâches {filter}',
      'new_task': 'Nouvelle tâche',
      'task_hint': 'Que faut-il faire ?',
      'add_task': 'Ajouter',
      'high': 'Haute',
      'medium': 'Moyenne',
      'low': 'Basse',
      'pomodoro': 'Pomodoro',
      'short_break': 'Pause courte',
      'long_break': 'Pause longue',
      'sessions': 'sessions',
      'focus_lock_on': 'Verrouillage focus activé',
      'stop_timer_before_leaving': 'Arrêtez le minuteur avant de partir !',
      'session_saved': 'session de min enregistrée ! 🎉',
      'tip1': '💡 Silencez votre téléphone pour un maximum de focus.',
      'tip2': '🌊 Prenez de grandes inspirations au début de chaque session.',
      'tip3': '✅ Écrivez votre tâche #1 avant de lancer le minuteur.',
      'tip4': '🎧 La musique d\'ambiance peut booster la concentration.',
    },
    'German': {
      'profile': 'Profil',
      'settings': 'Einstellungen',
      'notifications': 'Benachrichtigungen',
      'timer_duration': 'Timer-Dauer',
      'customise': 'Anpassen',
      'sounds': 'Töne',
      'theme': 'Design',
      'language': 'Sprache',
      'log_out': 'Abmelden',
      'edit_profile': 'Profil bearbeiten',
      'display_name': 'Anzeigename',
      'save_changes': 'Speichern',
      'total_sessions': 'Gesamte Sitzungen',
      'focus_hours': 'Fokus-Stunden',
      'tasks_done': 'Erledigte Aufgaben',
      'current_streak': 'Aktuelle Serie',
      'achievements': 'Erfolge',
      'home': 'Home',
      'focus': 'Fokus',
      'tasks': 'Aufgaben',
      'feed': 'Feed',
      'ai': 'KI',
      'on_fire': 'Heiß gelaufen',
      'speed_demon': 'Geschwindigkeits-Dämon',
      'sharpshooter': 'Scharfschütze',
      'night_owl': 'Nachtschwärmer',
      'champion': 'Champion',
      'diamond': 'Diamant',
      'streak_desc': '7-Tage-Serie',
      'sessions_desc': '10 Sitzungen erledigt',
      'tasks_desc': '50 Aufgaben erledigt',
      'night_desc': 'Fokus nach Mitternacht',
      'streak_30_desc': '30-Tage-Serie',
      'sessions_500_desc': '500 Sitzungen insgesamt',
      'all': 'Alle',
      'active_filter': 'Aktiv',
      'done_filter': 'Erledigt',
      'tasks_remaining': 'Aufgaben übrig',
      'completed_of': 'erledigt',
      'of': 'von',
      'no_tasks': 'Noch keine Aufgaben. Füge eine hinzu!',
      'no_filter_tasks': 'Keine {filter} Aufgaben',
      'new_task': 'Neue Aufgabe',
      'task_hint': 'Was steht an?',
      'add_task': 'Hinzufügen',
      'high': 'Hoch',
      'medium': 'Mittel',
      'low': 'Niedrig',
      'pomodoro': 'Pomodoro',
      'short_break': 'Kurze Pause',
      'long_break': 'Lange Pause',
      'sessions': 'Sitzungen',
      'focus_lock_on': 'Fokus-Sperre AN',
      'stop_timer_before_leaving': 'Timer vor dem Verlassen stoppen!',
      'session_saved': 'min Sitzung gespeichert! 🎉',
      'tip1': '💡 Schalte dein Handy stumm für maximalen Fokus.',
      'tip2': '🌊 Atme tief durch zu Beginn jeder Sitzung.',
      'tip3': '✅ Schreibe deine wichtigste Aufgabe auf, bevor du startest.',
      'tip4': '🎧 Ambient-Musik kann die Konzentration steigern.',
    },
  };

  static String t(String key) {
    final language = SettingsService.instance.language;
    return _translations[language]?[key] ?? _translations['English']![key] ?? key;
  }
}
