// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ3uiDB_48OhGZPlNrh63p8tIvM_ahdVk',
    appId: '1:579001057268:web:14feace00dae18c76883a1',
    messagingSenderId: '579001057268',
    projectId: 'focusflow-955c6',
    authDomain: 'focusflow-955c6.firebaseapp.com',
    databaseURL: 'https://focusflow-955c6-default-rtdb.firebaseio.com',
    storageBucket: 'focusflow-955c6.firebasestorage.app',
    measurementId: 'G-3614WLCYB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUrnPhXQIKcb76tUC2fLObgLfP11PlAYk',
    appId: '1:579001057268:android:ec6254d64ee20c4f6883a1',
    messagingSenderId: '579001057268',
    projectId: 'focusflow-955c6',
    databaseURL: 'https://focusflow-955c6-default-rtdb.firebaseio.com',
    storageBucket: 'focusflow-955c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlb9jiWuyxjzxhQ753wJR8wMQDLWwX8YY',
    appId: '1:579001057268:ios:0ef7d2df609242b56883a1',
    messagingSenderId: '579001057268',
    projectId: 'focusflow-955c6',
    databaseURL: 'https://focusflow-955c6-default-rtdb.firebaseio.com',
    storageBucket: 'focusflow-955c6.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlb9jiWuyxjzxhQ753wJR8wMQDLWwX8YY',
    appId: '1:579001057268:ios:0ef7d2df609242b56883a1',
    messagingSenderId: '579001057268',
    projectId: 'focusflow-955c6',
    databaseURL: 'https://focusflow-955c6-default-rtdb.firebaseio.com',
    storageBucket: 'focusflow-955c6.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ3uiDB_48OhGZPlNrh63p8tIvM_ahdVk',
    appId: '1:579001057268:web:4456de656b1f719c6883a1',
    messagingSenderId: '579001057268',
    projectId: 'focusflow-955c6',
    authDomain: 'focusflow-955c6.firebaseapp.com',
    databaseURL: 'https://focusflow-955c6-default-rtdb.firebaseio.com',
    storageBucket: 'focusflow-955c6.firebasestorage.app',
    measurementId: 'G-D5N58X2Z0E',
  );

}